# SoftwaresForAll Native CI configuration for C written projects
pipeline:
  setup:
    image: ubuntu:24.04
    commands:
      - apt update -y
      - apt install -y git wget unzip python3 build-essential cmake ninja-build
      - wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
      - unzip codeql-linux64.zip -d /opt
      - echo "export PATH=/opt/codeql:$PATH" >> ~/.bashrc
      - source ~/.bashrc
      - codeql version

  build:
    image: gcc:14
    commands:
      - mkdir -p build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - cmake --build . --parallel $(nproc)
      - cd ..

  codeql:
    image: ubuntu:24.04
    commands:
      - apt update -y
      - apt install -y unzip python3 build-essential cmake
      - wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
      - unzip codeql-linux64.zip -d /opt
      - export PATH="/opt/codeql:$PATH"
      - mkdir -p /tmp/codeql-db
      - codeql database create /tmp/codeql-db --language=cpp --command="cmake -Bbuild && cmake --build build"
      - codeql database analyze /tmp/codeql-db cpp-security-and-quality.qls --format=sarifv2.1.0 --output=codeql-results.sarif
      - echo "=== CodeQL Scan Completed ==="
      - ls -lh codeql-results.sarif

  artifacts:
    image: alpine:3
    commands:
      - mkdir -p artifacts
      - cp codeql-results.sarif artifacts/
    when:
      status: success
